name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-libchdr:
    uses: ./.github/workflows/libchdr.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - build-libchdr
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.26"

      - name: Download dependencies
        run: go mod download -x
      
      - name: Get compiled libchdr
        uses: actions/download-artifact@v8
        with:
          pattern: libchdr-*
          path: thirdparty/libchdr
      
      - name: Extract compiled libchdr
        run: |
          find thirdparty/libchdr -type f -name '*.tar' -execdir sh -c 'tar -xf "{}" && rm "{}"' \;
          ls -R thirdparty/libchdr

      - name: Test
        run: go test -v -race -exec sudo ./...
